### ISSUE TITLE
Cannot install new version 2.6.0 via `pip`

### ISSUE THREAD

**Issue by m-theisen** [editorconfig-checker/editorconfig-checker.python#21]
When trying to install the newest version (2.6.0) via `pip install editorconfig-checker` I get the following error:
```
Collecting editorconfig-checker
  Downloading editorconfig-checker-2.6.0.tar.gz (4.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/home/theisen/test/.env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/theisen/test/.env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/theisen/test/.env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-htfayfg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "/tmp/pip-build-env-htfayfg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 56, in __init__
          super().__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-htfayfg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/builder.py", line 83, in __init__
          self._module = Module(
        File "/tmp/pip-build-env-htfayfg4/overlay/lib/python3.10/site-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package editorconfig-checker-python
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Additional information:
- pip version: `22.2.2`
- python version: `3.10`
- OS: Arch Linux (confirmed that it throws the same error on an Ubuntu system)

**Comment by mmicu** [comment]
Hi, thanks for reporting the issue. Can you please temporarily revert to 2.4.0?

I will publish the fix in the evening.

**Comment by m-theisen** [comment]
Thanks for the quick responds, for now I already downgraded, which still works as expected.

**Comment by mmicu** [comment]
Can you please try now?

**Comment by kitu-sbruce** [comment]
I can confirm this as working with 2.6.1

```
root@e707027f0d56:/# python3 --version
Python 3.8.14
root@e707027f0d56:/# pip3 --version
pip 22.0.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by mmicu** [comment]
> I can confirm this as working with 2.6.1
> 
> 
> 
> ```
> 
> root@e707027f0d56:/# python3 --version
> 
> Python 3.8.14
> 
> root@e707027f0d56:/# pip3 --version
> 
> pip 22.0.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
> 
> ```
> 
> 

Cool, thanks for the quick feedback.
